# Remap 

set-option -g prefix C-a
unbind-key C-b
unbind-key C-d
unbind-key C-1
bind-key C-a send-prefix

unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -sg escape-time 5 # fix vim esc delay
set -g default-terminal "screen-256color" # ensures vim uses right $TERM color, default is "screen"
set -ga terminal-overrides ",*256col*:Tc" # fixes vim reproducing slightly wrong colors in tmux

# Make tmux window numbering start from 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Vim style paneselector
bind h select-pane -L
bind j select-pane -D
bind l select-pane -R
bind k select-pane -U

unbind d

unbind C-1
unbind C-2

# Resize pane
bind C-1 select-layout even-vertical
bind C-2 select-layout even-horizontal

bind c new-window -c "#{pane_current_path}"

# Easy toggle
bind s last-pane
bind Space last-window

bind S-h previous-window
bind S-l next-window

# Easy toggle
bind C-s last-pane
bind C-Space next-layout

# Change zoom panel to f
unbind z
bind f resize-pane -Z

# Vim-like copy-paste mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# Statusline
set-option -g status-justify centre
set-option -g status-style "fg=colour08"
set-option -g status-interval 1
set-option -g status-left-length 256
set-option -g status-right-length 256
set-option -g status-left ""
set-option -g status-right ""
set-window-option -g window-status-style "fg=default"
set-window-option -g window-status-current-style "fg=colour14"
set-window-option -g window-status-bell-style "fg=colour9"
set-window-option -g window-status-activity-style "fg=colour9"

# Add conditional zoom indicator
set-window-option -g window-status-format '#{?window_zoomed_flag,#[fg=colour8][#{window_name}],#{=15:window_name}}'
set-window-option -g window-status-current-format '#{?window_zoomed_flag,#[fg=colour14][#{window_name}],#{=15:#{window_name}}}'

set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
